services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Painel Visual para o Redis
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis